var __BLOCKEDSITES__ = [
  "*.ua",
  "*.10minutemail.com",
  "*.10minutemail.net",
  "*.1lordserials.info",
  "*.3dyuriki.com",
  "*.4freerussia.org",
  "*.4pda.ru",
  "9tv.co.il",
  "*.activatica.org",
  "*.adguard.com",
  "*.agents.media",
  "*.anime-portal.ru",
  "*.animedub.ru",
  "*.animego-online.org",
  "*.animego.today",
  "*.animelib.me",
  "*.animevost.tv",
  "*.antiwar.in",
  "*.antiwarcommittee.info",
  "*.appleinsider.ru",
  "*.appspot.com",
  "*.arbat.media",
  "*.archiveofourown.org",
  "*.aussiedlerbote.de",
  "*.azathabar.com",
  "*.azattyq.com",
  "*.bbc.com",
  "*.bbci.co.uk",
  "*.bellingcat.com",
  "*.bild.de",
  "*.bing.com",
  "*.blackseanews.net",
  "*.canva.com",
  "*.carousell.sg",
  "*.cdninstagram.com",
  "*.centre-t.com",
  "*.chatgpt.com",
  "*.cheapsms.ru",
  "*.cherta.media",
  "*.claude.ai",
  "*.colta.ru",
  "*.copilot.cx",
  "*.crocoblock.com",
  "*.cropp.com",
  "*.currenttime.tv",
  "*.cvedetails.com",
  "*.cyxymu.info",
  "*.daz3d.com",
  "*.deepstatemap.live",
  "*.delfi.ee",
  "*.delfi.lt",
  "*.delfi.lv",
  "*.dell.com",
  "*.dellcdn.com",
  "*.discours.io",
  "*.dnsstuff.com",
  "danbooru.donmai.us",
  "*.dossier.center",
  "*.dovod.online",
  "*.doxa.team",
  "*.dumskaya.net",
  "*.dw.com",
  "*.echofm.online",
  "*.echokavkaza.com",
  "*.ej.ru",
  "*.eporner.com",
  "*.euronews.com",
  "*.euroradio.fm",
  "*.eutrp.eu",
  "*.exler.ru",
  "*.expres.online",
  "*.facebook.com",
  "*.fapreactor.com",
  "*.fb.com",
  "*.fbcdn.net",
  "*.fbsbx.com",
  "*.flibusta.is",
  "*.fonge.org",
  "*.fortanga.org",
  "*.foxitsoftware.com",
  "*.freemedia.io",
  "*.freepng.ru",
  "*.furaffinity.net",
  "*.gagadget.com",
  "*.germania.one",
  "*.getoutline.com",
  "*.getsignal.news",
  "yt3.ggpht.com",
  "*.githubcopilot.com",
  "bard.google.com",
  "gemini.google.com",
  "news.google.com",
  "play.google.com",
  "*.grani.ru",
  "*.graty.me",
  "*.greenmangaming.com",
  "*.hdrezka.ag",
  "*.hentai.name",
  "*.hentaichan.live",
  "*.hide.me",
  "*.hochunaiti.com",
  "*.holod.media",
  "*.hostinger.com",
  "*.hs.fi",
  "*.idelreal.org",
  "*.ikianime.tv",
  "*.instagram.com",
  "*.intel.com",
  "*.is.fi",
  "*.istories.media",
  "*.itsmycity.ru",
  "*.jakpolak.com",
  "*.jauns.lv",
  "*.joyreactor.cc",
  "*.jsfiddle.net",
  "*.kaleido.ai",
  "*.kasparov.ru",
  "*.kavkaz-uzel.eu",
  "*.kavkazr.com",
  "*.kinogo.biz",
  "*.kinogo.fm",
  "*.knowyourmeme.com",
  "*.konachan.com",
  "*.korrespondent.net",
  "*.krymr.com",
  "*.kym-cdn.com",
  "*.lentachel.ru",
  "*.leonidvolkov.ru",
  "*.libgen.is",
  "*.libgen.li",
  "*.libgen.rs",
  "*.libgen.st",
  "*.linkedin.com",
  "*.livehdcams.com",
  "*.locals.md",
  "*.lolz.guru",
  "*.lostfilm.tv",
  "*.m.me",
  "*.mangahub.ru",
  "*.mangapoisk.com",
  "*.manticgames.com",
  "*.mdza.io",
  "*.mediazona.ca",
  "*.medium.com",
  "*.meduza.io",
  "*.memorialcenter.org",
  "*.merezha.co",
  "*.meta.com",
  "*.metacritic.com",
  "*.metla.press",
  "copilot.microsoft.com",
  "designer.microsoft.com",
  "*.mignews.com",
  "*.miniplay.com",
  "*.mintmanga.live",
  "*.myrotvorets.center",
  "echo.msk.ru",
  "*.navalny.com",
  "*.neputin.org",
  "*.netflix.com",
  "*.newsru.com",
  "*.newsru.co.il",
  "*.newtimes.ru",
  "*.nhentai.net",
  "*.nhentai.to",
  "*.nnmclub.to",
  "*.notion.so",
  "*.novaya.no",
  "*.novayagazeta.ru",
  "*.novayagazeta.eu",
  "*.novyny.live",
  "*.nyaa.si",
  "cdn.oaistatic.com",
  "*.oculus.com",
  "*.odessa.online",
  "*.openai.com",
  "*.openmedia.io",
  "*.opposition-news.com",
  "*.osti.gov",
  "*.otkrito.lv",
  "*.ovd.info",
  "*.ovd.news",
  "*.ovdinfo.org",
  "*.ozodi.org",
  "*.pap.pl",
  "*.paperpaper.ru",
  "*.paperpaper.io",
  "*.patreon.com",
  "*.pixiv.net",
  "*.politiken.dk",
  "*.posle.media",
  "*.postimees.ee",
  "*.proekt.media",
  "*.provereno.media",
  "*.putin-killer.com",
  "*.quest.com",
  "*.quora.com",
  "*.radiosakharov.org",
  "*.realist.online",
  "*.remove.bg",
  "*.rentry.co",
  "*.republic.ru",
  "*.rezka.ag",
  "*.rezonans.media",
  "*.rferl.org",
  "*.roar-review.com",
  "*.root-nation.com",
  "*.rule34.xxx",
  "*.rutor.info",
  "*.rutor.is",
  "*.rutracker.net",
  "*.rutracker.nl",
  "*.rutracker.org",
  "*.sakhalin.info",
  "*.sakharovfoundation.org",
  "*.saverudata.net",
  "*.scrolller.com",
  "*.semnasem.org",
  "*.severreal.org",
  "*.shikimori.me",
  "*.sibreal.org",
  "*.skat.media",
  "*.slavicsac.com",
  "*.smartasset.com",
  "*.sobesednik.com",
  "*.sobytiya.info",
  "*.solopress.com",
  "*.sotaproject.com",
  "*.sotavision.world",
  "*.soundcloud.com",
  "*.spektr.press",
  "*.spotify.com",
  "*.sputnikipogrom.com",
  "*.strana.news",
  "*.strana.today",
  "*.suicidegirls.com",
  "*.surveymonkey.com",
  "*.suspilne.media",
  "*.svoboda.org",
  "*.svtv.org",
  "*.syg.ma",
  "*.t.co",
  "*.t-ru.org",
  "*.tayga.info",
  "*.te-st.org",
  "*.telegraf.by",
  "*.temp-mail.org",
  "*.tempmail.plus",
  "*.temporary-email.org",
  "*.the-village.ru",
  "*.thebarentsobserver.com",
  "*.thebell.io",
  "*.theins.ru",
  "*.themegrill.com",
  "*.thenewtab.io",
  "*.thepiratebay.org",
  "*.tjournal.ru",
  "*.top-fon.com",
  "*.torrentgalaxy.to",
  "*.torproject.org",
  "*.tv2.today",
  "*.tvfreedom.io",
  "*.tvrain.ru",
  "*.tvrain.tv",
  "*.twimg.com",
  "*.twitter.com",
  "*.unian.net",
  "*.usa.one",
  "*.verstka.media",
  "*.verpex.com",
  "*.vesma.today",
  "*.vesma.one",
  "vesty.co.il",
  "*.voanews.com",
  "*.vot-tak.tv",
  "*.vpnlove.me",
  "*.vynesimozg.com",
  "*.wdfiles.com",
  "*.weather.com",
  "*.welt.de",
  "*.wikidot.com",
  "*.willytel.de",
  "*.windscribe.com",
  "*.wixmp.com",
  "*.wonderzine.com",
  "*.x.com",
  "*.yande.re",
  "*.yaoilib.me",
  "*.yle.fi",
  "*.yummyanime.org",
  "*.zahav.ru",
  "*.zerkalo.io",
  "*.zona.media",
  "*.zomro.com"
];

var proxy;
var direct;

if (typeof __PROXY__ === "undefined") {
    proxy = "SOCKS5 127.0.0.1:1080; SOCKS 127.0.0.1:1080";
    direct = "DIRECT";
} else {
    proxy = __PROXY__;
    direct = "DIRECT;";
}

var FindProxyForURL = function(init, profiles) {
    return function(url, host) {
        "use strict";
        var result = init, scheme = url.substr(0, url.indexOf(":"));
        do {
            result = profiles[result];
            if (typeof result === "function") result = result(url, host, scheme);
        } while (typeof result !== "string" || result.charCodeAt(0) === 43);
        return result;
    };
}("+auto switch", {
    "+auto switch": function(url, host, scheme) {
        "use strict";
        if (__BLOCKEDSITES__.some(function(blockedSite) {
            return new RegExp((blockedSite.startsWith("*") ? "(?:^|\\.)" : "^") + blockedSite.replace(/\./g, "\\.").replace(/^\*\\\./, "") + "$").test(host);
        })) {
            return "+proxy";
        }
        return "DIRECT";
    },
    "+proxy": function(url, host, scheme) {
        "use strict";
        if (/^127\.0\.0\.1$/.test(host) || /^::1$/.test(host) || /^localhost$/.test(host) || /^192\.168\.[0-9]{1-3}\.[0-9]{1-3}$/.test(host)) {
            return direct;
        }
        return proxy;
    }
});
